# Generated by Django 4.2.5 on 2023-09-26 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdr', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='patienceRecord',
            new_name='patientRecords',
        ),
    ]
