# Generated by Django 4.2.5 on 2023-10-03 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdr', '0003_alter_patientrecords_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientrecords',
            options={},
        ),
        migrations.AlterModelManagers(
            name='patientrecords',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='patientrecords',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='patientrecords',
            name='email',
        ),
        migrations.RemoveField(
            model_name='patientrecords',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='patientrecords',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='patientrecords',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='patientrecords',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='patientrecords',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='patientrecords',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='patientrecords',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='patientrecords',
            name='password',
        ),
        migrations.RemoveField(
            model_name='patientrecords',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='patientrecords',
            name='username',
        ),
    ]
